apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: fastapi-app-ci
  title: FastAPI App CI
  description: An example template that builds FastAPI docker image and push it to the Artifact Registry
  tags:
    - backstage
    - fastapi
spec:
  owner: user:guest
  type: service

  parameters:
    - title: FastAPI App Build
      required:
        - project_id
        - cloudrun_service_name
      properties:
        project_id:
          title: Project Name
          type: string
          description: Name of the Project to deploy
        cloudrun_service_name:
          title: Cloud Run Service Name
          type: string
          description: Name of the Cloud Run Service
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./content
        values:
          project_id: ${{ parameters.project_id }}
          cloudrun_service_name: ${{ parameters.cloudrun_service_name }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        defaultBranch: main
        description: This is FastAPI app
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: public
        protectDefaultBranch: false
        
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}