apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.cloudrun_service_name | dump }}
  annotations:
    backstage.io/project: ${{ values.project_id | dump }}
    backstage.io/source-location: url:https://github.com/monkmantra/fastapi
    github.com/project-slug: monkmantra/fastapi
    backstage.io/techdocs-ref: dir:.
  description: Fastapi Cloud Run service
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
