name: Build docker image ${{ values.cloudrun_service_name }}

on:
  push:
    branches: main
{% raw %}
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
env:
  GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
  GCP_SERVICE_ACCOUNT: ${{ vars.GCP_SERVICE_ACCOUNT }}
    
jobs:
  build-fastapi-app:
    name: Build FastAPI App
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: configure gcp credentials
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}

      - name: auth docker
        run: gcloud --quiet auth configure-docker us-east4-docker.pkg.dev
      
      - name: Build and push
        run: |
          docker build --tag "us-east4-docker.pkg.dev/png-gcp-learning-poc/python-fastapi/${{ values.cloudrun_service_name }}:${{github.run_number}}" .
      
      - name: Push to artifact registry
        run: |
          docker push us-east4-docker.pkg.dev/png-gcp-learning-poc/python-fastapi/${{ values.cloudrun_service_name }}:${{github.run_number}}
          gcloud container images add-tag us-east4-docker.pkg.dev/png-gcp-learning-poc/python-fastapi/${{ values.cloudrun_service_name }}:${{github.run_number}} us-east4-docker.pkg.dev/png-gcp-learning-poc/python-fastapi/${{ values.cloudrun_service_name }}:latest
{% endraw %}  
